export const FIRST_NAME = [
    `Himura`,
    `Daichi`,
    `Eiko`,
    `Genji`,
    `Mizu`,
    `Isamu`,
    `Toyo`,
    `Ryoma`,
    `Michiko`,
    `Tomoe`,
    `Osamu`,
    `Rei`,
    `Sachi`,
    `Saito`,
    `Ume`,
    `Yori`,
    `Zen`,
    `Arata`,
    `Jiro`,
    `Musashi`,
    `Akihiro`,
    `Botan`,
    `Chika`,
    `Daigo`,
    `Etsuko`,
    `Fumio`,
    `Gendo`,
    `Hoshiko`,
    `Ichiro`,
    `Jun`,
    `Kaede`,
    `Katsuro`,
    `Masaki`,
    `Noboru`,
    `Renka`,
    `Sadao`,
    `Takumi`,
    `Umeko`,
    `Yori`,
    `Zanka`,
];

export const LAST_NAMES = [
    `Battosai`,
    `Chiba`,
    `Fujiwara`,
    `Hattori`,
    `Ito`,
    `Matsamune`,
    `Sakura`,
    `Sakamoto`,
    `Okada`,
    `Hajime`,
    `Takahashi`,
    `Uesugi`,
    `Yamagata`,
    `Yojimbo`,
    `Akiyama`,
    `Fujimoto`,
    `Miyamoto`,
    `Ishikawa`,
    `Kitano`,
    `Matsushita`,
    `Ayanami`,
    `Chikamatsu`,
    `Dazai`,
    `Ebihara`,
    `Fujikawa`,
    `Gōda`,
    `Hayashi`,
    `Ishibashi`,
    `Jinno`,
    `Kamizawa`,
    `Kuroda`,
    `Minamoto`,
    `Nakamura`,
    `Okabe`,
    `Ryuzaki`,
    `Saotome`,
    `Takayama`,
    `Yagami`,
    `Zenko`,
    'Bando',
];

export const NICKNAMES = [
    `The Hawk's Eye / Taka no Me`,
    `The Dragon of the Sea / Umi no Tatsu`,
    `Thunder Fang / Kaminari no Kiba`,
    `River God / Kawa no Kami`,
    `Mountain Wind / Yama no Kaze`,
    `Sword Saint of the Wind / Kaze no Kensei`,
    `Demon of the Fog / Kiri no Oni`,
    `Tiger of Hell / Jigoku no Tora`,
    `Fox of the Night / Yoru no Kitsune`,
    `Black Fang / Kuroi Kiba`,
    `Tiger Demon / Tora no Oni`,
    `Cat's Paw / Neko no Te`,
    `Wind Tengu / Kaze no Tengu`,
    `Man Slayer / Hitokiri`,
    `Knight of Darkness / Yami no Kishi`,
    `Monster Boss / Bakemono no Oyabun`,
    `Flower Geisha / Hana no Geisha`,
    `Warrior of Thunder / Kaminari no Senshi`,
    `Ghostly Wanderer / Yurei no Tomurai`,
    `Black Shadow / Kuroi Kage `,
    `Black Swallow / Kuroi Tsubame`,
    `Shadow Wind / Kaze no Yami`,
    `Iron Fang / Tetsu Kiba`,
    `Snow of Hell / Jigoku no Yuki`,
    `Demon Feather / Hane no Oni`,
    `Crimson Mist / Akai Kiri`,
    `Scarlet Thunder / Shinku Kaminari`,
    `River Ghost / Kawa no Yurei`,
    `Eye of the Crow / Karasu no Me`,
    `Silent Tiger / Shizuka Tora`,
    `Flower of Darkness / Yami no Hana`,
    `Blood Crane / Chi no Tsuru`,
    `World Between / Utsushiyo`,
    `Thunder Monk / Kaminari Sho¯Nin`,
    `Invisible Feather / To¯Mei Hane`,
    `Sweet Death / Amai Shi`,
    `Voice of Higan / Higan no Koe`,
    `Swan Spirit / Hakucho¯ Reikon`,
    `White Claw / Shiroi Tsume`,
    `Rat of the Night / Yoru no Nezumi`,
]

